
SELECT
h.DOCID AS DOC_ID,
h.DOCTYPE AS INVOICE_TYPE,
h.INDEX_DATE AS ENTRY_DATE,
h.CHANGE_DATE AS LAST_CHANGE_DATE,
h.STATUS AS STATUS_ID,
h.BUKRS AS  COMPANY_CODE,
h.BLART AS DOC_TYPE,
h.BLDAT AS DOC_DATE,
h.BUDAT AS POSTING_DATE,
h.XBLNR AS INVOICE_NUMBER,
h.RMWWR AS AMOUNT,
h.LIFNR AS VENDOR_NUM,
h.VEND_NAME AS VENDOR_NAME_1,
h.VEND_NAME2 AS VENDOR_NAME_2,
h.EBELN AS PO_NUM,
h.DUE_DATE AS DUE_DATE,
h.BARCODE AS CODING_GROUP,
h.VENDOR_VAT_NO AS ABN,
h.BELNR_FI AS ACCOUNTING_DOC_NUM,
h.SNAPSHOT_DT AS DSS_DOWNLOAD_DATE,
t.OBJTXT AS STATUS_TEXT,
r.MAIL_S AS SENDER_EMAIL,
r.REGID AS REG_ID,
r.LAYOUT_ID AS LAYOUT_ID,
r.TSP_REGISTER AS ENTRY_DATE_AND_TIME,
e.LASTCHANGEDATETIME AS PO_LAST_UPDATED,
r.FEEDB_LEARN,
r.TRNG_LEARN,
r.REJ_REASON,
r.STATUS AS EXTRACT_STATUS
FROM DSS.VIM_1HEAD_2HEAD_VW h
LEFT JOIN DSS.VIM_STG_T101T_VW t ON h.STATUS = t.STATUSID
LEFT JOIN DSS.ps4_ekko_lastchangedatetime_vw e ON e.EBELN = h.EBELN
LEFT JOIN DSS.vim_otx_pf01_t_1reg_ap_vw r ON r.target_projkey = h.DOCID
WHERE h.index_date >= TO_DATE('2023-07-01', 'YYYY-MM-DD') OR h.BUDAT >= TO_DATE('2023-07-01', 'YYYY-MM-DD')
ORDER BY ENTRY_DATE DESC, BUDAT DESC