
SELECT
h.DOCID,
h.DOCTYPE,
h.INDEX_DATE,
h.CHANGE_DATE,
h.STATUS,
h.BUKRS,
h.BLART,
h.BLDAT,
h.BUDAT,
h.XBLNR,
h.RMWWR,
h.LIFNR,
h.VEND_NAME,
h.VEND_NAME2,
h.EBELN,
h.DUE_DATE,
h.BARCODE,
h.VENDOR_VAT_NO,
h.BELNR_FI,
h.SNAPSHOT_DT,
t.STATUSID,
t.OBJTXT AS STATUS_TEXT,
r.MAIL_S,
r.TARGET_PROJKEY,
r.LAYOUT_ID,
r.TSP_REGISTER,
e.EBELN,
e.LASTCHANGEDATETIME
FROM DSS.VIM_1HEAD_2HEAD_VW h
LEFT JOIN DSS.VIM_STG_T101T_VW t ON h.STATUS = t.STATUSID
LEFT JOIN DSS.ps4_ekko_lastchangedatetime_vw e ON e.EBELN = h.EBELN
LEFT JOIN DSS.vim_otx_pf01_t_1reg_ap_vw r ON r.target_projkey = h.DOCID
WHERE h.index_date >= TO_DATE('2023-07-01', 'YYYY-MM-DD')