SELECT
Lfb.BUKRS AS COMPANY_CODE,
Lfa.LIFNR AS VENDOR_NUM,
Lfa.NAME1 AS VENDOR_NAME_1,
Lfa.NAME2 AS VENDOR_NAME_2,
Lfa.ERDAT AS VENDOR_CREATION_DATE,
Lfa.KTOKK AS VENDOR_ACCOUNT_GROUP,
Lfb.ZTERM AS PAYMENT_TERMS_ID,
t.TEXT1 AS PAYMENT_TERMS,
Lfb.SPERR AS POSTING_BLOCK,
Lfb.ZAHLS AS PAYMENT_BLOCK,
Lfa.ORT01 AS CITY,
Lfa.STRAS AS STREET,
Lfa.LNRZA AS ALTERNATE_PAYEE,
Lfa.TELF1 AS TELEPHONE_1,
Lfb.AKONT AS RECONCILIATION_ACCOUNT,
b.TYPE AS OTET_VENDOR_INDICATOR,
b.ENTRY_DATE AS OTET_VENDOR_CREATION_DATE,
TO_CHAR(b.VALID_DATE_FROM, 'YYYY-MM-DD') AS OTET_VENDOR_START_DATE,
TO_CHAR(b.VALID_DATE_TO, 'YYYY-MM-DD') AS OTET_VENDOR_END_DATE
FROM DSS.FS4_STG_LFB1_VW lfb
JOIN DSS.FS4_STG_T052U_VW t ON lfb.ZTERM = t.ZTERM
JOIN DSS.FS4_STG_LFA1_VW lfa ON lfa.LIFNR = lfb.LIFNR
LEFT JOIN DSS.VIM_STG_BUT0ID_V b ON lfa.LIFNR = b.PARTNER
ORDER BY Lfa.LIFNR, Lfb.BUKRS

