SELECT
Lfb.BUKRS,
Lfa.LIFNR,
Lfa.NAME1,
Lfa.NAME2,
Lfa.ERDAT,
Lfa.KTOKK,
Lfb.ZTERM,
t.TEXT1 AS PAYMENT_TERMS,
Lfb.SPERR,
Lfb.ZAHLS,
Lfa.ORT01,
Lfa.STRAS,
Lfa.LNRZA,
Lfa.TELF1,
Lfb.AKONT,
b.TYPE,
b.ENTRY_DATE,
TO_CHAR(b.VALID_DATE_FROM, 'YYYY-MM-DD') AS VALID_DATE_FROM,
TO_CHAR(b.VALID_DATE_TO, 'YYYY-MM-DD') AS VALID_DATE_TO
FROM DSS.FS4_STG_LFB1_VW lfb
JOIN DSS.FS4_STG_T052U_VW t ON lfb.ZTERM = t.ZTERM
JOIN DSS.FS4_STG_LFA1_VW lfa ON lfa.LIFNR = lfb.LIFNR
LEFT JOIN DSS.VIM_STG_BUT0ID_V b ON lfa.LIFNR = b.PARTNER
ORDER BY Lfa.LIFNR, Lfb.BUKRS

