SELECT
Lfa.LIFNR,
Lfa.NAME1,
Lfa.NAME2,
Lfa.ORT01,
Lfa.STRAS,
Lfa.ERDAT,
Lfa.KTOKK,
Lfa.LNRZA,
Lfa.TELF1,
Lfb.LIFNR,
Lfb.ZTERM,
Lfb.BUKRS,
Lfb.SPERR,
Lfb.AKONT,
Lfb.ZAHLS,
t.ZTERM,
t.TEXT1,
b.PARTNER,
b.TYPE,
b.ENTRY_DATE,
b.VALID_DATE_FROM,
b.VALID_DATE_TO

FROM DSS.FS4_STG_LFB1_VW lfb
JOIN DSS.FS4_STG_T052U_VW t ON lfb.ZTERM = t.ZTERM
JOIN DSS.FS4_STG_LFA1_VW lfa ON lfa.LIFNR = lfb.LIFNR
LEFT JOIN DSS.VIM_STG_BUT0ID_V  b ON lfa.LIFNR = b.PARTNER
WHERE ROWNUM <= 10000
